name: Infra Deployment and Training

on:
  push:
    paths: 
      - '.github/workflows/setup.yml'
 
 
# CONFIGURATION 
#
# 1. Set up the following secrets in your repository: 
#   AZURE_RESOURCE_GROUP 
#   STORAGE_ACCOUNT 
env:
  AZURE_RESOURCE_GROUP: your-resource-group-name   #set this to your resource group name 
  #STORAGE_ACCOUNT: storage-account-name           #set this to your storage-account-name
    
jobs:
  deployment:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploys Azure resources 
    - name: Deploy Azure resources
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/deploy.core-infra.json \
            --parameters $GITHUB_WORKSPACE/infra/params.deploy.core-infra.json \
            patToken=${{secrets.PATTOKEN}} repo_name=$GITHUB_REPOSITORY DataLakestorageName=${{ env.STORAGE_ACCOUNT }}
